// CREATE USER
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "user 1",
  "email": "user1@gmail.com",
  "password": "1234",
  "confirmPassword": "1234",
  "role": "user"
}

###
// GET ALL USER
// ONLY ADMIN CAN ACCESS THIS REQUEST
GET http://localhost:5000/users

###
// UPDATE USER DATA BASED ON UUID
PATCH http://localhost:5000/users/e0000d13-3e2b-49d6-9388-b16019c0b29a
Content-Type: application/json

{
  "name": "staff_1 updated",
  "email": "staff_1@gmail.com",
  "password": "",
  "confirmPassword": "",
  "role": "user"
}

###
// DELETE USER BASED ON UUID
DELETE http://localhost:5000/users/e0000d13-3e2b-49d6-9388-b16019c0b29a

###
// LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1234"
}

###
// LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1234"
}

###
// GET CURRENT USER
GET http://localhost:5000/me

###
// LOGOUT CURRENT USER
DELETE http://localhost:5000/logout

###
// GET ALL PRODUCTS
GET http://localhost:5000/products

###
// GET SINGLE PRODUCTS
GET http://localhost:5000/products

###
// CREATE PRODUCT
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Product 5",
  "price": "1000"
}

